name: Minecraft server

on:
  push:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Java JRE
      uses: actions/setup-java@v1.3.0
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 1.8
        # The package type (jre, jdk, jdk+fx)
        java-package: jre

    - uses: actions/checkout@v2
    - name: Setup server
      env:
        skfrp_username: ${{ secrets.skfrp_username }}
        skfrp_password: ${{ secrets.skfrp_password }}
      run: |
        ./frp/frpc --su=$skfrp_username --sp=$skfrp_password --sid=1 &
        java -server -Xms3G -Xmx3G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+UseLargePagesInMetaspace -Dusing.aikars.flags=mcflags.emc.gs -jar paperclip.jar
